import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { ethers } from "ethers";
import React, { useState, useEffect } from "react";
import { utils, providers } from "ethers";
import { BrowserRouter, Switch, Route, useHistory } from "react-router-dom";
import Transaction from "./Transaction";

export default function Home() {
  const [inputTx, setInputTx] = useState("");
  const ethers = require("ethers");
  const provider = new ethers.providers.JsonRpcProvider(
    "https://side-radial-brook.discover.quiknode.pro/ef97ef143b347d61c7752d85820db07bf0d8ff02/"
  );

  const getInputTx = async () => {
    //0x5bdf7ab01ec7c7670f61a011e82ccc273bb8756d800af081e99c9f890c655ed1
    const txInfo = await provider.send("eth_getTransactionByHash", [inputTx]);
    var number = txInfo.blockNumber;
    var ha = txInfo.blockHash;
    var gas = txInfo.gas;
    setInputTx(txInfo);
    console.log(inputTx);
  };

  (async () => {
    const provider = new ethers.providers.JsonRpcProvider(
      "https://side-radial-brook.discover.quiknode.pro/ef97ef143b347d61c7752d85820db07bf0d8ff02/"
    );
    const txInfo = await provider.send("eth_getTransactionByHash", [
      "0x0ec3f2488a93839524add10ea229e773f6bc891b4eb4794c3337d4495263790b",
    ]);
    console.log("testing", txInfo);
  })();

  return (
    <div className={styles.container}>
      <Head>
        <title>Social Media Block Explorer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">SociaPlorer!</a>
        </h1>
        <div className={styles.grid}>
          <input
            /* onChange={(e) => setInputTx(e.target.value)} */
            placeholder="Find Transaction Hash"
          ></input>

          <button onClick={getInputTx}>Search</button>

          <BrowserRouter>
            <Switch>
              <Route path="/transaction" component={Transaction} />
            </Switch>
          </BrowserRouter>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
